<a href="https://colab.research.google.com/github/cyc1974/BPI2019/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. PyTorch Fundamentals
resoure notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

source code https://github.com/mrdbourke/pytorch-deep-learning


In [56]:
#查看版本
!nvidia-smi

Thu Nov 10 03:52:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [57]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


##introduction to Tensors

###Creating tensor

Pytorch tensor are careted using https://pytorch.org/docs/stable/tensors.html


In [58]:
#scalar
scalar=torch.tensor([[1, 2, 3], [4, 5, 6]])
scalar

tensor([[1, 2, 3],
        [4, 5, 6]])

In [59]:
scalar.ndim

2

In [60]:
#get tensor back as python int
scalar.shape

torch.Size([2, 3])

In [61]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
###Random tensors
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.1743, 0.5816, 0.4032, 0.8485],
        [0.4847, 0.8511, 0.0075, 0.6347],
        [0.2687, 0.2988, 0.8602, 0.7321]])

In [65]:
random_tensors.ndim

2

In [66]:
random_tensors.shape

torch.Size([3, 4])

In [67]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #3=RGB
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [68]:
# Create a tensor of all zero
zeros1 = torch.zeros([3,4])
zeros1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
zeros2 = torch.ones(3,4)
zeros2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
torch.arange(1,11) #int
torch.range(1,11) #float
temp=torch.arange(1,11,2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


In [71]:
#create tensors like temp count (創建與temp相同個數的0值)
ten_zeros = torch.zeros_like(temp)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [72]:
#3個tensor重要參數
#dtype 型態 float32 or flat16
#device 設備 gpu or cpu
#requrise_grad 是否使用梯度追蹤
ten_32 = torch.tensor([3.0,6.0,9.0],dtype=None, #default torch.dtype=float32
                      device=None, #GPU(cuda) or CPU 
                      requires_grad=False)
ten_32.dtype

torch.float32

In [73]:
#直接將float32轉為float16
ten_16 = ten_32.type(torch.float16)
ten_16.dtype

torch.float16

In [74]:
ten_32 * ten_16

tensor([ 9., 36., 81.])

In [75]:
### Getting information from tensor
#dtype 型態 float32 or flat16 => tensor.dtype
#device 設備 gpu or cpu =>tensor.shape
#requrise_grad 是否使用梯度追蹤 => tensor.device

In [76]:
some_tensor = torch.tensor([3.,4.])
some_ten16 = some_tensor.type(torch.float16)
print(some_tensor)
print(f'some_ten16 dtype:,{some_ten16.dtype}')
print(f'some_ten16 device:,{some_ten16.device}')
print(f'some_ten16 shape:,{some_ten16.shape}')

tensor([3., 4.])
some_ten16 dtype:,torch.float16
some_ten16 device:,cpu
some_ten16 shape:,torch.Size([2])


###tensor  
* 加減
* 乘除
* 矩陣



In [77]:
tensor = torch.tensor([2,3,4])
print(f'tensor + 10:{tensor + 10}')
print(f'tensor - 10:{tensor - 10}')
print(f'tensor * 10:{tensor * 10}')
print(f'tensor / 10:{tensor / 10}')



tensor + 10:tensor([12, 13, 14])
tensor - 10:tensor([-8, -7, -6])
tensor * 10:tensor([20, 30, 40])
tensor / 10:tensor([0.2000, 0.3000, 0.4000])


In [78]:
%%time
tensor * tensor
print(torch.matmul(tensor,tensor))

tensor(29)
CPU times: user 8.97 ms, sys: 0 ns, total: 8.97 ms
Wall time: 8.84 ms


In [79]:
%%time
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(132)
CPU times: user 390 µs, sys: 0 ns, total: 390 µs
Wall time: 398 µs


###兩個tensor相乘，內在矩陣維度必須相同，例如
###tensor1=(3,2) tensor2=(3,2) =>(3,2) @ (3,2) 
###tensor1[1],tensor2[0]=>則稱之為內在矩陣，此時2<>3,所以內在矩陣並不相同
 

In [80]:
torch.matmul(torch.rand(3,2), torch.rand(2,2)).shape

torch.Size([3, 2])

In [81]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]] 
                        )
tensor_B = torch.tensor([[7,8],[9,10],[11,12]] 
                        )
#error
torch.mm(tensor_A,tensor_B)




RuntimeError: ignored

In [82]:
#To fix our tensor shape issue
#inner dimensions must match
tensor_B.T,tensor_B.T.shape

torch.mm(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

#Finding the min,max,mean,sum


In [83]:
x = torch.arange(0,100,10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [84]:
torch.min(x)

tensor(0)

In [85]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [89]:
x
torch.sum(x)


tensor(0)

In [90]:
x.argmin()

tensor(0)

In [91]:
x.argmax()

tensor(9)