<a href="https://colab.research.google.com/github/cyc1974/BPI2019/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. PyTorch Fundamentals
resoure notebook https://www.learnpytorch.io/00_pytorch_fundamentals/

source code https://github.com/mrdbourke/pytorch-deep-learning


In [2]:
#查看版本
!nvidia-smi

Wed Nov  9 11:10:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


##introduction to Tensors

###Creating tensor

Pytorch tensor are careted using https://pytorch.org/docs/stable/tensors.html


In [5]:
#scalar
scalar=torch.tensor([[1, 2, 3], [4, 5, 6]])
scalar

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
scalar.ndim

2

In [9]:
#get tensor back as python int
scalar.shape

torch.Size([2, 3])

In [13]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
###Random tensors
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.5592, 0.0682, 0.4207, 0.9538],
        [0.1454, 0.4998, 0.5061, 0.8894],
        [0.2874, 0.3483, 0.2495, 0.7533]])

In [19]:
random_tensors.ndim

2

In [20]:
random_tensors.shape

torch.Size([3, 4])

In [22]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #3=RGB
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
# Create a tensor of all zero
zeros1 = torch.zeros([3,4])
zeros1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zeros2 = torch.ones(3,4)
zeros2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
torch.arange(1,11) #int
torch.range(1,11) #float
temp=torch.arange(1,11,2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


In [40]:
#create tensors like temp count (創建與temp相同個數的0值)
ten_zeros = torch.zeros_like(temp)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [48]:
#3個tensor重要參數
#dtype 型態 float32 or flat16
#device 設備 gpu or cpu
#requrise_grad 是否使用梯度追蹤
ten_32 = torch.tensor([3.0,6.0,9.0],dtype=None, #default torch.dtype=float32
                      device=None, #GPU(cuda) or CPU 
                      requires_grad=False)
ten_32.dtype

torch.float32

In [50]:
#直接將float32轉為float16
ten_16 = ten_32.type(torch.float16)
ten_16.dtype

torch.float16

In [51]:
ten_32 * ten_16

tensor([ 9., 36., 81.])

In [ ]:
### Getting information from tensor
#dtype 型態 float32 or flat16 => tensor.dtype
#device 設備 gpu or cpu =>tensor.shape
#requrise_grad 是否使用梯度追蹤 => tensor.device

In [61]:
some_tensor = torch.tensor([3.,4.])
some_ten16 = some_tensor.type(torch.float16)
print(some_tensor)
print(f'some_ten16 dtype:,{some_ten16.dtype}')
print(f'some_ten16 device:,{some_ten16.device}')
print(f'some_ten16 shape:,{some_ten16.shape}')

tensor([3., 4.])
some_ten16 dtype:,torch.float16
some_ten16 device:,cpu
some_ten16 shape:,torch.Size([2])
