# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch

import torch

# Create random tensor
x=torch.rand(7,7)

x,x.shape

(tensor([[0.1552, 0.3299, 0.2444, 0.8922, 0.6902, 0.3432, 0.1033],
         [0.9041, 0.2250, 0.8319, 0.7467, 0.0776, 0.0882, 0.8574],
         [0.9032, 0.7483, 0.6146, 0.8083, 0.7626, 0.6040, 0.6233],
         [0.4620, 0.3050, 0.2789, 0.4093, 0.1083, 0.8284, 0.2612],
         [0.0378, 0.7013, 0.9807, 0.3446, 0.1331, 0.5550, 0.7289],
         [0.4683, 0.8603, 0.6495, 0.2841, 0.3546, 0.3075, 0.1098],
         [0.5650, 0.1779, 0.0759, 0.7242, 0.5759, 0.8690, 0.6182]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
y = torch.rand(1,7)
# Perform matrix multiplication 
z = torch.matmul(x,y.T)
print(f'x:{x}')
print(f'y:{y}')
print(f'z:{z}')
z,z.shape

x:tensor([[0.1552, 0.3299, 0.2444, 0.8922, 0.6902, 0.3432, 0.1033],
        [0.9041, 0.2250, 0.8319, 0.7467, 0.0776, 0.0882, 0.8574],
        [0.9032, 0.7483, 0.6146, 0.8083, 0.7626, 0.6040, 0.6233],
        [0.4620, 0.3050, 0.2789, 0.4093, 0.1083, 0.8284, 0.2612],
        [0.0378, 0.7013, 0.9807, 0.3446, 0.1331, 0.5550, 0.7289],
        [0.4683, 0.8603, 0.6495, 0.2841, 0.3546, 0.3075, 0.1098],
        [0.5650, 0.1779, 0.0759, 0.7242, 0.5759, 0.8690, 0.6182]])
y:tensor([[0.4085, 0.3695, 0.9924, 0.4334, 0.9944, 0.4303, 0.0449]])
z:tensor([[1.6531],
        [1.7552],
        [2.6518],
        [1.2314],
        [1.8011],
        [1.7667],
        [1.6600]])


(tensor([[1.6531],
         [1.7552],
         [2.6518],
         [1.2314],
         [1.8011],
         [1.7667],
         [1.6600]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x=torch.rand(7,7)
y=torch.rand(1,7)

# Matrix multiply tensors
z = torch.matmul(x,y.T)
z,z.shape

(tensor([[0.9454],
         [0.9473],
         [0.7089],
         [1.4405],
         [1.3714],
         [0.9152],
         [0.9704]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
ts_a = torch.rand(2,3).to(device)
ts_b = torch.rand(2,3).to(device)
print(f'device:{device}')
ts_a, ts_b

cpu
device:cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]), tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
tensor_c = torch.matmul(ts_a,ts_b.T)
tensor_c,tensor_c.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
tensor_c.max()
# Find min
tensor_c.min()

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Find arg max

tensor_c.argmax()
# Find arg min
tensor_c.argmin()

tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed

torch.manual_seed(7)
# Create random tensor
x = torch.rand(1,1,1,10)

# Remove single dimensions
y =x.squeeze()


# Print out tensors and their shapes
x.shape,y.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))